### ISSUE TITLE
Github Actions Limits

### ISSUE THREAD

**Issue by peteowen1** [jimmyday12/fitzroy_data#19]
Didn't know about the limits beforehand but seems like there's a 2000-minute GitHub action limit for the month, which has been hit.

Can either try running
https://github.com/jimmyday12/fitzroy_data/blob/main/scripts/afltables_weekly_script.R
locally and then pushing (although this will kick-off another action workflow which will have to be stopped).

Or can just wait 'til start of next month.

Think the Footywire full rescrape taking ~3hrs added up a bit over this month - but reverting back to only doing the past year or two should mean we shouldn't get this issue going forward

**Comment by jimmyday12** [comment]
Thanks for uncovering that and good to know the limits. I'm away at the moment but back next week so will take a closer look, but sounds like waiting for the new month  and then reducing the time for the Footywire rescrape would be good.
